cmake_minimum_required(VERSION 3.20)
project(SecureTTY C)

set(CMAKE_C_STANDARD 23)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
find_package(raylib 5.0 REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(SODIUM REQUIRED libsodium)
pkg_check_modules(MYSQL REQUIRED mysqlclient)

add_executable(client client.c)
add_executable(server server.c)
target_link_libraries(client PRIVATE raylib GL m pthread dl rt X11 Xrandr Xinerama Xi Xcursor OpenSSL::SSL OpenSSL::Crypto ${SODIUM_LIBRARIES})
target_link_libraries(server PRIVATE m pthread OpenSSL::SSL OpenSSL::Crypto ${MYSQL_LIBRARIES} ${SODIUM_LIBRARIES})
target_include_directories(client PRIVATE ${CMAKE_SOURCE_DIR}/build_include ${SODIUM_INCLUDE_DIRS})
target_include_directories(server PRIVATE ${MYSQL_INCLUDE_DIRS} ${SODIUM_INCLUDE_DIRS})
